LDAP setup options - CA certs, STARTTLS, user schema
bihealth/sodar-docker-compose pull request #43
Opened 2023-09-25 15:15 UTC by HaraldWilhelmi

Matching pull request to https://github.com/bihealth/sodar-server/pull/1799.

2023-09-26 14:19 UTC, mikkonie requested changes
Apart from one minor typo this looks good. Nice and thorough comments for the environment and config examples.

2023-09-26 14:19 UTC, mikkonie commented on env.example
> +# To us it:
This should probably say "use" :)

2023-09-27 07:56 UTC, HaraldWilhelmi commented
To keep the commit history clean I just force-pushed a new commit. Please check.

2023-09-27 08:38 UTC, mikkonie approved these changes
Approved, thanks for the PR.

2023-09-27 08:39 UTC, merged